Boolean("x");
Boolean("");
Boolean("false");
Boolean(0);
Boolean(1);
Boolean(Infinity);
Boolean(null);
Boolean(undefined);
Boolean({});
Boolean([]);

console.log(!!"x");
console.log(!!"");
console.log(!!"false");
console.log(!!0);
console.log(!!1);
console.log(!!null);
console.log(!![]);
console.log(!!{});
